### ISSUE TITLE
Doesn't the ATP subnet resource need the "prohibit_public_ip_on_vnic = true" argument?

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-quickstart/oci-arch-atp-private#1]
In `subnet_atp_endpoint.tf`, don't we need to add  `prohibit_public_ip_on_vnic = true` , to designate the ATP subnet as private?

**Comment by lfeldman** [comment]
@kumar-dhanagopal you are right, I have fixed that in the latest commit https://github.com/oracle-quickstart/oci-arch-atp-private/commit/8992f3fc7bade7e494f1619a9d7469fc46ab8e0d).
