### ISSUE TITLE
Update the prereqs section

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-quickstart/oci-arch-atp-private#3]
The permissions & quota prereqs should be updated to reflect specific requirements for this stack.

**Comment by lfeldman** [comment]
I have updated the prereqs. New commit merged: https://github.com/oracle-quickstart/oci-arch-atp-private/commit/b5e332188121c012814b9939d128d50c73cee6d9

**Comment by kumar-dhanagopal** [comment]
Thank you, @lfeldman !
